/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nfaPlanetaryMarketSol from "./NFAPlanetaryMarket.sol";
export type { nfaPlanetaryMarketSol };
