"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EVMBridge__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var EVMBridge__factory_1 = require("./EVMBridge__factory");
Object.defineProperty(exports, "EVMBridge__factory", { enumerable: true, get: function () { return EVMBridge__factory_1.EVMBridge__factory; } });
//# sourceMappingURL=index.js.map